### ISSUE TITLE
How to share links via Folio?

### ISSUE THREAD

**Issue by sfilmak** [creativetrendsapps/FolioforFacebook#1]
Hello!
Please, publish sharing code from Folio which allow to share links from another apps via Folio:
![photo_2016-10-01_18-12-06](https://cloud.githubusercontent.com/assets/7964443/19014978/3bd4c91c-8803-11e6-84cc-6d4bd188bf1f.jpg)

Thank you in advance!

**Comment by creativetrendsapps** [comment]
This actually isn't an issue. This source code can actually share to Facebook from another app already. Check the code [Here].(https://github.com/creativetrendsapps/FolioforFacebook/blob/master/app/src/main/java/com/creativtrendz/folio/activities/MainActivity.java#L1150)
