### ISSUE TITLE
Issue with notifications

### ISSUE THREAD

**Issue by ZeeRooo** [creativetrendsapps/FolioforFacebook#2]
Hello, im trying to port this notifications to my app (isnt in play store, is for past my time). My problem is this:
_10-08 23:06:38.452 31967-31967/me.zeeroooo.materialfb I/NotificationsService: ********** Service created! **********
10-08 23:06:41.458 31967-32308/me.zeeroooo.materialfb I/NotificationsService: Time interval: 120 seconds
10-08 23:06:41.463 31967-32308/me.zeeroooo.materialfb I/NotificationsService: RuntimeException caught
10-08 23:06:41.468 31967-31967/me.zeeroooo.materialfb I/NotificationsService: onDestroy: Service stopping...
10-08 23:06:41.474 31967-31967/me.zeeroooo.materialfb I/NotificationsService: ********** Service created! **********
10-08 23:06:44.480 31967-32384/me.zeeroooo.materialfb I/NotificationsService: Time interval: 120 seconds
10-08 23:06:44.489 31967-32384/me.zeeroooo.materialfb I/NotificationsService: RuntimeException caught
10-08 23:06:44.504 31967-31967/me.zeeroooo.materialfb I/NotificationsService: onDestroy: Service stopping...
10-08 23:06:44.518 31967-31967/me.zeeroooo.materialfb I/NotificationsService: ********** Service created! **********_

I dont know how to fix this, probably you can help me. The code is here:

- ZeeRooo/MaterialFBook@a846a11
- https://github.com/ZeeRooo/MaterialFBook/tree/Testing
Thanks and sorry if this is a spam.

**Comment by creativetrendsapps** [comment]
As this isnt an issue related to Folio (your app is forked from tinfoil and your notification code is forked from FaceSlim) I'm closing this issue.
