### ISSUE TITLE
ImageGrabber

### ISSUE THREAD

**Issue by sfilmak** [creativetrendsapps/FolioforFacebook#3]
Hi!
Please, add [ImageGrabber ](https://github.com/creativetrendsapps/FolioforFacebook/blob/d2c6b8a70404154261042ab5907fade2ffa19a69/app/src/main/java/com/creativtrendz/folio/activities/PhotoViewer.java#L213)file to Utils folder, because PhotoViewer need this file to share image from Facebook.
Thank you in advance!

**Comment by creativetrendsapps** [comment]
ImageGrabber isn't necessary and can be removed.

**Comment by sfilmak** [comment]
Okay. 
I'm sorry, but the're no another way to get this file?

**Comment by creativetrendsapps** [comment]
@sfilmak , there isn't a need for the file. Sharing an image doesn't actual depend on it so it can be removed from that portion of code. It's no longer in Folio's source code so there isn't a way to add it.

**Comment by sfilmak** [comment]
Oh, thank you!

**Comment by creativetrendsapps** [comment]
Sorry, this issue cannot be closed yet as ImageGrabber is required.

**Comment by sfilmak** [comment]
Thank you very much again!
